Use reusable workflows
vazco/uniforms pull request #1076
Opened 2021-12-16 09:56 UTC by Monteth

Before you open a pull request, please check if a similar one already exists or has been closed before. Detailed information about the process of contributing can be found in [CONTRIBUTING.md](https://github.com/vazco/uniforms/blob/master/.github/CONTRIBUTING.md).

Do link all relevant issues and pull requests. If there is none, please do file an issue first to discuss it upfront.

2021-12-21 13:14 UTC, wadamek65 commented
Pasting our discussion on slack for visibility:

Could you perhaps take a look if maybe one of these approaches could be better instead?
* Define the action as a task using a docker action (https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)
* Take a look at DangerJS to see if maybe it has plugins for these operations (https://danger.systems/js/)

2022-01-19 14:47 UTC, radekmie requested changes
Could `npm_vuln_check` be a step as well?

2022-01-19 14:47 UTC, radekmie commented on .github/workflows/CI.yml
> +      - name: Npm dependency duplication check
Can we keep the step name as it was? I think it was better before.

2022-05-31 10:28 UTC, wadamek65 submitted a review, later dismissed

2022-06-01 06:18 UTC, zendranm submitted a review, later dismissed

2022-06-13 08:21 UTC, wadamek65 commented
@Monteth 

> Please take a look if it suits us. I think the vuln report is very nice, but the dedupe is not telling much.

Where can I see that?

2022-06-13 09:36 UTC, Monteth commented
> @Monteth
> 
> > Please take a look if it suits us. I think the vuln report is very nice, but the dedupe is not telling much.
> 
> Where can I see that?

Go to Checks
![image](https://user-images.githubusercontent.com/17573948/173324735-dea83431-602b-4a7e-8e5e-b3c5ff4a5e59.png)
Then click on the CI workflow
![image](https://user-images.githubusercontent.com/17573948/173324968-249302d7-c12f-42b0-897c-4e2041e1a7dc.png)

2022-06-13 09:48 UTC, wadamek65 commented
@Monteth Ah, for some reason I was expecting a separate job and forgot it was built into our current CI workflow 🤦 looks good 👌

2022-06-24 10:10 UTC, merged