Make AutoFields render a Fragment wrapper
vazco/uniforms pull request #1173
Opened 2022-10-08 11:56 UTC by wadamek65

Closes https://github.com/vazco/uniforms/issues/1133

Note: Recreated for Hacktoberfest contribution.

2022-10-12 17:46 UTC, radekmie requested changes

2022-10-12 17:46 UTC, radekmie commented on docs/migrating-3-to-4.md
> +- `AutoFields` component in all themes now renders a `React.Fragment` instead of a `div`. Explicitly render a wrapper component around if you need one.
Let's discuss it briefly, but we should add this file to the main branch and point this PR against it.

2022-10-12 17:46 UTC, radekmie commented on packages/uniforms-antd/src/AutoFields.tsx
> +import { ComponentType, createElement, Fragment } from 'react';
Let's keep these ordered (`Fragment` should go before `createElement`).

2022-10-14 13:02 UTC, kestarumper approved these changes

2022-10-18 19:24 UTC, radekmie approved these changes

2022-10-18 19:25 UTC, merged