Replace property `allowedValues` + `transform` with `options`
vazco/uniforms pull request #1229
Opened 2023-02-24 14:04 UTC by kestarumper

This PR closes #806.

2023-03-31 11:41 UTC, radekmie requested changes

2023-03-31 11:41 UTC, radekmie commented on docs/uth-autofield-algorithm.md
> +  if (props.options) {
Can you add the `if (props.component)` part here too? It's missing in the docs.

2023-03-31 11:41 UTC, radekmie commented on packages/uniforms-antd/src/RadioField.tsx
> +        >
We could add the `disabled` here as well.

2023-03-31 11:41 UTC, radekmie commented on packages/uniforms-antd/src/types.ts
> +export type Option<Value = unknown> = {
We pass the `Value` everywhere, so there's no need for a default here.

2023-03-31 11:41 UTC, radekmie commented on packages/uniforms-antd/src/types.ts
> +  label: string;
Isn't the `label` optional as well?

2023-03-31 11:41 UTC, radekmie commented on packages/uniforms-bootstrap3/src/RadioField.tsx
> +        <label htmlFor={`${props.id}-${escape(item.key ?? item.value)}`}>
There's no need to `escape` the `key`:
```suggestion
        <label htmlFor={`${props.id}-${item.key ?? escape(item.value)}`}>
```

2023-03-31 11:41 UTC, radekmie commented on packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts
> +        label: String(value),
I wouldn't add it here, as `label` fallbacks to `value` anyway.

2023-03-31 11:41 UTC, radekmie commented on packages/uniforms-bridge-simple-schema-2/__tests__/SimpleSchema2Bridge.ts
>        });
It'd be better to test the entire `options`, not only some properties. It'll also make the test smaller.

2023-03-31 11:41 UTC, radekmie commented on packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts
> +  });
1. As above, there's no need to provide `key` and `label`.
2. There's no point in making it a method - either inline it entirely, or make a helper outside of the class.

2023-04-14 14:09 UTC, radekmie commented on packages/uniforms-bridge-zod/src/ZodBridge.ts
> +        label: value,
I'd leave these out as they're optional and default to `value` anyway.

2023-04-15 15:27 UTC, radekmie approved these changes

2023-04-28 09:12 UTC, zendranm approved these changes

2023-05-12 07:44 UTC, merged