Migrated `LongTextField` tests to @testing-library/react
vazco/uniforms pull request #1268
Opened 2023-05-26 09:36 UTC by piotrpospiech

Migrated `LongTextField` tests to @testing-library/react

2023-06-02 10:56 UTC, ErnestTeluk requested changes

2023-06-02 10:56 UTC, ErnestTeluk commented on packages/uniforms/__suites__/BoolField.tsx
> +  if (options?.testCheckbox) {
Now you can change this to skipTestIf function

2023-06-05 09:39 UTC, radekmie submitted a review, later dismissed
We'll definitely have to think about _not_ having so many flags in this suite, but that can come later.

2023-06-16 09:55 UTC, radekmie submitted a review, later dismissed

2023-06-16 10:43 UTC, Monteth submitted a review, later dismissed

2023-06-16 11:47 UTC, ErnestTeluk approved these changes

2023-06-16 11:53 UTC, zaxoavoki approved these changes

2023-06-19 12:38 UTC, radekmie approved these changes

2023-06-19 12:38 UTC, merged