Recursive schema evaluation - stop evaluating initial value for empty array
vazco/uniforms pull request #1282
Opened 2023-08-11 14:42 UTC by Monteth

2024-05-10 10:35 UTC, kestarumper approved these changes

2024-05-27 13:15 UTC, kestarumper commented
We talked internally with @Monteth, and we also want to include a basic cycle detection mechanism to prevent freezing the browser tab (prevent infinite loops).

2024-06-14 09:12 UTC, ErnestTeluk approved these changes

2025-01-19 17:36 UTC, Monteth commented
> We talked internally with @Monteth, and we also want to include a basic cycle detection mechanism to prevent freezing the browser tab (prevent infinite loops). 

I've tried to implement that, but since it is a little more complicated than we would like, I want to merge this PR without this check and (eventually) implement it under a dedicated issue.

I'd also reconsider if we really need that because I've spotted only one issue related to JSONSchema infinite loop (#596) that was fixed. This PR fixes one more case where it could take place so that it will be even less helpful but still will have an impact on the package footprint and render performance. 

@kestarumper

2025-01-20 08:33 UTC, piotrpospiech requested changes
I think you have some leftovers from trying to implement loops detection.

2025-01-20 08:33 UTC, piotrpospiech commented on package.json
> +    "buffer": "^5.5.0||^6.0.0",
Why two different versions? It is dev depenendency, not a peer dependency. Why is this needed? Where is this used?

2025-01-20 08:33 UTC, piotrpospiech commented on package.json
> +    "json-schema-traverse": "1.0.0",
Why is it added here? It was already added to the json bridge package.

2025-01-20 08:33 UTC, piotrpospiech commented on package.json
> +    "process": "^0.11.10",
Is this used?

2025-01-20 08:33 UTC, piotrpospiech commented on packages/uniforms-bridge-json-schema/package.json
> +    "json-schema-traverse": "^1.0.0",
Where did you use it?

2025-01-23 10:47 UTC, Monteth commented
> I think you have some leftovers from trying to implement loop detection.

Yes, indeed. Sorry for that!

2025-01-23 11:08 UTC, piotrpospiech approved these changes

2025-01-24 11:21 UTC, zendranm approved these changes

2025-02-28 07:38 UTC, piotrpospiech requested changes

2025-02-28 07:38 UTC, piotrpospiech commented on pnpm-lock.yaml
> +      '@parcel/workers': 2.12.0(@parcel/core@2.12.0(@swc/helpers@0.5.13))
You should remove `pnpm-lock.yaml` from this PR. It looks like changes caused by packages installed previously.

2025-02-28 09:07 UTC, piotrpospiech approved these changes

2025-02-28 12:54 UTC, merged