Rewrite `SelectField` tests
vazco/uniforms pull request #1294
Opened 2023-11-09 23:35 UTC by zaxoavoki

Before you open a pull request, please check if a similar one already exists or has been closed before. Detailed information about the process of contributing can be found in [CONTRIBUTING.md](https://github.com/vazco/uniforms/blob/master/.github/CONTRIBUTING.md).

Do link all relevant issues and pull requests. If there is none, please do file an issue first to discuss it upfront.

2024-03-08 09:06 UTC, kestarumper requested changes
Missing tests for
- [ ] AntD
- [ ] Material
- [ ] MUI

2024-03-08 09:56 UTC, Monteth approved these changes

2024-03-08 10:43 UTC, zaxoavoki commented on packages/uniforms/__suites__/render-zod.tsx
> -      }
Because the prop types say that `schema` is a true value, so there is no need to check the opposite condition.

2024-03-08 10:47 UTC, zaxoavoki commented on packages/uniforms/__suites__/SelectField.tsx
> +  });
Sure.

2024-04-05 11:02 UTC, kestarumper approved these changes

2024-04-05 11:03 UTC, merged