Added support for Zod `.refine` and `.superRefine`
vazco/uniforms pull request #1319
Opened 2024-04-20 12:09 UTC by piotrpospiech

This allows to pass to the `ZodBridge` schema that has `refine` or `superRefine`.

**Example:**

```ts
const schema = z
  .object({
    username: z.string().min(4),
    password: z.string().min(8),
    confirmPassword: z.string().min(8),
  })
  .refine((form) => form.password === form.confirmPassword, {
    message: "Passwords don't match",
    path: ["confirmPassword"],
  });
```

```ts
const schema = z
  .object({
    username: z.string().min(4),
    password: z.string().min(8),
    confirmPassword: z.string().min(8),
  })
  .superRefine((val, ctx) => {
    if (val.password !== val.confirmPassword) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Passwords don't match",
        path: ["confirmPassword"],
      });
    }
  });
``` 

<img width="324" alt="image" src="https://github.com/vazco/uniforms/assets/37746259/b0af40e3-ed0c-49c0-9fee-5df326eba317">

2024-04-23 06:52 UTC, kestarumper requested changes
Could you add a simple test that creates the `ZodBridge` from a `z.object(...).refine()` and `z.object(...).superRefine()`?

2024-04-23 20:22 UTC, kestarumper approved these changes

2024-05-24 07:09 UTC, zaxoavoki approved these changes

2024-05-24 07:55 UTC, zendranm approved these changes

2024-05-24 08:20 UTC, Monteth approved these changes

2024-05-24 08:40 UTC, merged