Deprecate `uniforms-bridge-graphql` package
vazco/uniforms pull request #1322
Opened 2024-04-20 15:37 UTC by piotrpospiech

Deprecate the GraphQL bridge, as mentioned in this issue (https://github.com/vazco/uniforms/issues/1315).

- Removed the whole package from the `uniforms` repository
- Removed package from labeler
- Removed GraphQL from the Readme file
- Removed `graphql` and `uniforms-bridge-graphql` packages from `package.json` files
- Removed GraphQL example from docs (playground)

> [!NOTE]
> I left the `GraphQLBridge` docs. We will keep that in the uniforms v3 docs.

2024-04-23 06:59 UTC, kestarumper requested changes
If we leave the docs about the GraphQL bridge, shouldn't we add a warning that the package has been deprecated? I suggest using [admonition](https://docusaurus.io/docs/next/markdown-features/admonitions).

2024-05-10 10:40 UTC, kestarumper approved these changes

2024-05-24 08:09 UTC, zendranm approved these changes

2024-05-24 08:30 UTC, Monteth approved these changes

2024-05-24 09:32 UTC, merged