Deprecate `uniforms-bridge-simple-schema` package
vazco/uniforms pull request #1323
Opened 2024-04-20 16:16 UTC by piotrpospiech

Deprecate the Meteor SimpleSchema bridge, as mentioned in this issue (https://github.com/vazco/uniforms/issues/1315).

- Removed the whole package from the uniforms repository
- Removed package from the labeler
- Removed SimpleSchema from the Readme file
- Removed the `uniforms-bridge-simple-schema` package from the `package.json` files
- Removed bridge from `tsconfig` references
- Removed mocks and removed `__mocks__` directory config

> [!NOTE]
> I left the `SimpleSchemaBridge` docs. We will keep that in the uniforms v3 docs.

2024-04-23 07:14 UTC, kestarumper requested changes
Let's add [warn admonition](https://docusaurus.io/docs/next/markdown-features/admonitions) to mark it in the docs as deprecated.

2024-05-10 10:45 UTC, kestarumper submitted a review, later dismissed

2024-05-24 08:09 UTC, zendranm submitted a review, later dismissed

2024-05-24 08:39 UTC, Monteth approved these changes

2024-05-24 16:23 UTC, zaxoavoki approved these changes

2024-05-27 13:28 UTC, kestarumper approved these changes

2024-06-03 07:27 UTC, merged