Added readonly attribute.
vazco/uniforms pull request #835
Opened 2020-12-07 11:49 UTC by martachrzanowska

This change provides support for the `readonly` attribute.

Closes #674.

2020-12-11 11:20 UTC, radekmie requested changes
I've added a few examples of how we could simplify this code quite a lot. Everything else is fine :rocket:

2020-12-11 11:20 UTC, radekmie commented on packages/uniforms-antd/src/ListDelField.tsx
> +        } else {
```suggestion
        if (!readOnly) {
```

2020-12-11 11:20 UTC, radekmie commented on packages/uniforms-antd/src/ListAddField.tsx
> +          : parent.onChange(parent.value!.concat([cloneDeep(value)]))
```suggestion
        if (!readOnly) {
          parent.onChange(parent.value!.concat([cloneDeep(value)]));
        }
```

2020-12-11 11:20 UTC, radekmie commented on packages/uniforms-antd/src/DateField.tsx
> +          : props.onChange(value ? value.toDate() : undefined);
```suggestion
        if (!props.readOnly)
          props.onChange(value ? value.toDate() : undefined);
        }
```

2020-12-11 11:20 UTC, radekmie commented on packages/uniforms-unstyled/src/BoolField.tsx
> +        onChange={() => (disabled || readOnly ? undefined : onChange(!value))}
```suggestion
        onChange={() => (!disabled && !readOnly && onChange(!value))}
```

2020-12-15 09:46 UTC, radekmie approved these changes

2020-12-21 10:01 UTC, radekmie submitted a review, later dismissed

2020-12-21 10:04 UTC, Monteth submitted a review, later dismissed

2021-02-03 12:24 UTC, radekmie approved these changes

2021-02-03 12:36 UTC, merged