Respect initial count in not required list fields (fixes #875).
vazco/uniforms pull request #907
Opened 2021-03-17 14:52 UTC by Monteth

2021-03-18 08:29 UTC, radekmie commented on packages/uniforms-antd/src/ListAddField.tsx
> +  initialCount = 0,
I think that we don't need this default, right? Bridges do have fallback anyway.

2021-03-18 08:29 UTC, radekmie commented on packages/uniforms-antd/src/ListAddField.tsx
> +    { maxCount?: number; initialCount: number },
```suggestion
    { initialCount?: number; maxCount?: number },
```

2021-03-22 09:28 UTC, radekmie submitted a review, later dismissed
Code is fine. Let's add tests first though.

2021-03-26 09:12 UTC, radekmie requested changes
In the meantime, the `uniforms-bootstrap5` got created - could you update it as well?

2021-03-26 09:12 UTC, radekmie commented on packages/uniforms-antd/__tests__/ListField.tsx
> +  ]); // renders ( initialCount + 1 ) default values
1. I'd remove this comment.
2. Could you add a test with a different default value as well?

2021-03-26 12:51 UTC, michael-vasyliv commented
@radekmie do we need to fix this issue for bootstrap5 as well?

2021-03-26 12:52 UTC, radekmie commented
@michael-vasyliv Yes, I already mentioned that.

2021-03-31 11:57 UTC, radekmie approved these changes

2021-03-31 11:58 UTC, merged